spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: com.luwei.common.config.JpaNamingStrategy
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
  datasource:
    url: jdbc:mysql://193.112.251.82:3307/PROJECT?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: PROJECT
    password: DmeY3s0CqCNUwFFA
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      max-active: 30
      initial-size: 3
      min-idle: 3
      max-idle: 10
  redis:
    port: 6381
    host: 193.112.251.82
    password: q7FIqKnrILC98sTeb2Z2
    database: 0
    timeout: 5000ms
    jedis:
      pool:
        min-idle: 3
        max-idle: 10
        max-active: 20
        max-wait: -1ms
  messages:
    basename: messages


swagger:
  show: true