# server通用配置(web模块 dev/test默认9115 pro为9115)
server:
  port: 9115
  error:
    whitelabel:
      enabled: false
  undertow:
    accesslog:
      enabled: true
  connection-timeout: 10000ms
  compression:
    enabled: true

# spring通用配置
spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: always
    serialization:
      write-dates-as-timestamps: true
  http:
    encoding:
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB
  # 连接池配置
  datasource:
    hikari:
      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 3
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，
      #建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      max-lifetime: 1500000
      #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 300000
      #连接只读数据库时配置为true， 保证安全
      read-only: false


  cache:#

# 模块化的配置
luwei:
  qiniu:
    bucket: edin
    access-key: 9YThA2ZpNq4UnyRRz_ZigkzgH6davcLehUPogG4C
    secret-key: RoZdZeQ8_a0efxTRMisMufPZbTQxLrBy3flc4kLf
    link-address: http://edin.halohealth.cn/
  module:
    sms:
      redus-prefix:
      access-key-id:
      access-key-secret:
      sign-name:
      template-code:
      template-code-name:

    shiro:
      prefix: student-hosting-web
      cors-urls: /api/user/**,/api/classify/**,/api/search,/api/keyword/**
      anon-urls: /api/login/captcha,/api/login,/api/module/qiniu/**,/api/weChat/authorize,/api/module/pay/wechat/notify,/**

    wx:
      appId: wx286aefff1a6b3c75
      appSecret: a41ea923e49dac2bf1ecd2144d6e8b9b
    # 微信支付相关参数
    pay:
      wechat:
        appid: wx286aefff1a6b3c75
        mchId: 1521645131
        mchKey: asdjfdsafwa933fsfafk03irkokfpivk
        notifyUrl: http://student-hosting-web.t.haikevr.com/api/module/pay/wechat/notify
        deviceInfo:

wechat:
  mchId: 1521645131
  spbillCreateIp: 127.0.0.1
  mchKey: asdjfdsafwa933fsfafk03irkokfpivk


# swagger开关/默认打开
swagger:
  show: true


