url: jdbc:mysql://193.112.251.82:3307/student-hosting?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
driverClassName: com.mysql.jdbc.Driver
username: student-hosting
password: bzsFBIP98MSUFg6K
tableNames:
  - tb_school



beanNames: school

#VO、dto位置
voDTODir: pojo.cms


packageName: com.luwei
tablePrefix: tb_
logicDeleteFieldName: deleted
versionFieldName: version
restControllerStyle: true
author: zzx

#是否覆盖
isOverEntity: true
isOverController: true
isOverService: true
isOverServiceImpl: true
isOverMapper: true

#是否在java目录下生成
isOverXml: false


entityVM : /templates/entity.vm
controllerVM : /templates/controller.vm
serviceVM :
serviceImplVM: /templates/service.vm
mapperVM :
xmlVM :
