url: jdbc:mysql://localhost:3306/mybatisplus?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
driverClassName: com.mysql.jdbc.Driver
username: root
password: 123456
tableNames:
  - tb_notice


packageName: com.luwei
tablePrefix: tb_
logicDeleteFieldName: deleted
versionFieldName: version
restControllerStyle: true
author: ffq

isOverEntity: true
isOverController: false
isOverService: false
isOverServiceImpl: false
isOverMapper: false
isOverXml: false


entityVM : /templates/entity.vm
controllerVM : /templates/controller.vm
serviceVM :
serviceImplVM:
mapperVM :
xmlVM :
