url: jdbc:mysql://119.23.227.7:3306/student_hosting?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
username: root
password: 123456
driverClassName: com.mysql.cj.jdbc.Driver

packageName: com.luwei
tablePrefix: tb_

#是否全表生成
isAllTablesGenerator: false

#支持多表 or 排除的表（isAllTablesGenerator:true时，tableNames表示排除的表名）
tableNames:
  - course_commit
#  - tb_test

logicDeleteFieldName: deleted
versionFieldName: version
restControllerStyle: true
author: ffq

#是否覆盖
isOverEntity: true
isOverController: true
isOverService: true
isOverServiceImpl: true
isOverMapper: true

#是否在java目录下生成
isOverXml: false


entityVM: /templates/entity.vm
controllerVM: /templates/controller.vm
serviceVM:
serviceImplVM: /templates/service.vm
mapperVM: /templates/mapper.java.vm
xmlVM: /templates/mapper.xml.vm
