url: jdbc:mysql://193.112.251.82:3307/student-hosting?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
username: student-hosting
password: bzsFBIP98MSUFg6K
driverClassName: com.mysql.jdbc.Driver

packageName: com.luwei
tablePrefix: tb_

#是否全表生成
isAllTablesGenerator : false

#支持多表 or 排除的表（isAllTablesGenerator:true时，tableNames表示排除的表名）
tableNames:
  - tb_mini_user
#  - tb_test

logicDeleteFieldName: deleted
versionFieldName: version
restControllerStyle: true
author: ffq

#是否覆盖
isOverEntity: true
isOverController: true
isOverService: true
isOverServiceImpl: true
isOverMapper: true

#是否在java目录下生成
isOverXml: false


entityVM : /templates/entity.vm
controllerVM : /templates/controller.vm
serviceVM :
serviceImplVM: /templates/service.vm
mapperVM : /templates/mapper.java.vm
xmlVM : /templates/mapper.xml.vm
