# mybatis相关配置
mybatis-plus:
  # 扫描枚举包
  type-enums-package: com.luwei.model.**;com.luwei.common.constant
  # MyBatis Mapper 所对应的 XML 文件位置
  mapper-locations: classpath*:mapper/*.xml
  # MyBaits 别名包扫描路径，注册后在Mapper对应的XML文件中可以直接使用类名，
  # 而不用使用全限定的类名（即XML中调用的时候不用包含包名）
  # type-aliases-package: com.luwei.model
  configuration:
    # 使用驼峰法映射属性,配置这个resultType可以映射
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: tb_

# 日志打印级别 DEBUG < INFO < WARN < ERROR
logging:
  level:
    com.luwei: debug