# Mybatis-plus配置
mybatis-plus:
  #MyBatis Mapper 所对应的 XML 文件位置
  mapper-locations: classpath*:mapper/**/*.xml
#  MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，
#注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）
  typeAliasesPackage: com.luwei.models
  configuration:
    map-underscore-to-camel-case: true  #使用驼峰法映射属性,配置这个resultType可以映射
  global-config:
    db-config:
      table-prefix: tb_

logging:
  level:
    com.baomidou.mybatisplus.samples: debug