server:
  error:
    whitelabel:
      enabled: false
  undertow:
    accesslog:
      enabled: true
  connection-timeout: 10000ms
  compression:
    enabled: true
  port: 8081

spring:
  profiles:
    active: dev

  jackson:
    default-property-inclusion: always
    serialization:
      write-dates-as-timestamps: true

  http:
    encoding:
      charset: UTF-8

  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB

luwei:
  config:
    salt: 3u492ijdf*89q34l882jk
  qiniu:
    bucket:
    access-key:
    secret-key:
    link-address:
  module:
    sms:
      redus-prefix:
      access-key-id:
      access-key-secret:
      sign-name:
      template-code:
      template-code-name:
    shiro:
      rule: project-templet-cms
      cache-days: 15
      token-prefix: ${server.port}
      token-name: auth.token.
      anon-urls: /api/picCaptcha,/api/login,/api/module/qiniu/**
      cors-urls: /api/user/**,/api/classify/**,/api/search,/api/keyword/**
      auth-urls: /api/**
