spring:
  datasource:
    url: jdbc:mysql://119.23.227.7:3306/student_hosting?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6381
    host: 193.112.251.82
    password: q7FIqKnrILC98sTeb2Z2
    database: 12
    timeout: 5000ms
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 3
        # 最大空闲连接数 默认8
        max-idle: 3
        # 最小空闲连接数 默认0
        min-idle: 0
  messages:
    basename: messages

debug: true