# server通用配置(cms模块 dev/test默认9114 pro为9114)
server:
  port: 9114
  error:
    whitelabel:
      enabled: false
  undertow:
    accesslog:
      enabled: true
  connection-timeout: 10000ms
  compression:
    enabled: true

# spring通用配置
spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: always
    serialization:
      write-dates-as-timestamps: true
  http:
    encoding:
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: com.luwei.common.config.JpaNamingStrategy
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect

# Mybatis-plus配置在dao模块

# 模块化的配置
luwei:
  config:
    salt: 3u492ijdf*89q34l882jk
  module:
    qiniu:
      bucket:
      access-key:
      secret-key:
      link-address:
    sms:
      redus-prefix:
      access-key-id:
      access-key-secret:
      sign-name:
      template-code:
      template-code-name:
    shiro:
      rule: student-hosting-cms
      cache-days: 15
      token-prefix: ${server.port}
      token-name: auth.token.
      cors-urls: /api/user/**,/api/classify/**,/api/search,/api/keyword/**
      anon-urls: /api/picCaptcha,/api/login,/api/module/qiniu/**
      auth-urls: /api/**

# swagger开关/默认打开
swagger:
  show: true

