spring:
  datasource:
    # 配127.0.0.1
    url: jdbc:mysql://127.0.0.1:3307/student-hosting?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: student-hosting
    password: bzsFBIP98MSUFg6K
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    port: 6381
    host: 193.112.251.82
    password: q7FIqKnrILC98sTeb2Z2
    database: 12
    timeout: 5000ms
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 3
        # 最大空闲连接数 默认8
        max-idle: 3
        # 最小空闲连接数 默认0
        min-idle: 0
  messages:
    basename: messages