server:
  port: 9117

spring:
  datasource:
    url: jdbc:mysql://193.112.251.82:3307/student-hosting?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: student-hosting
    password: bzsFBIP98MSUFg6K
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      max-lifetime: 1800000
      connection-timeout: 30000
      idle-timeout: 600000
      read-only: false

  redis:
    port: 6381
    host: 193.112.251.82
    password: q7FIqKnrILC98sTeb2Z2
    database: 12
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
  messages:
    basename: messages

swagger:
  show: false