spring:
  datasource:
    url: jdbc:mysql://193.112.251.82:3307/student-hosting?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: student-hosting
    password: bzsFBIP98MSUFg6K
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 150000
      maximum-pool-size: 3
      connection-timeout: 30000
      idle-timeout: 300000
      read-only: false


  redis:
    port: 6381
    host: 193.112.251.82
    password: q7FIqKnrILC98sTeb2Z2
    database: 12
    timeout: 5000ms
    lettuce:
      pool:
        min-idle: 3
        max-idle: 10
        max-active: 20
        max-wait: -1ms
  messages:
    basename: messages